@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam componentStyle rectangle

title GoldenCompass Architecture

actor user
artifact file

component Ui
component Parser
component Executor
component Storage
component Main
component Command

user -right.> Ui
Ui -.> user
Main --> Ui
Main --> Parser
Main --> Executor
Storage -right.> file
Storage -up.> Main
Parser -left-> Ui
Executor -left-> Parser
Executor -down-> Command
Executor --> Ui
Executor -right[hidden]- Storage
@enduml