@startuml
hide footbox
skinparam maxMessageSize 150

participant ":RejectOfferCommand" as RejectOfferCommand #ADD1B2
participant "parser:Parser" as Parser #ADD1B2
participant "internshipList:InternshipList" as InternshipList #F498AD
participant "internship:Internship" as Internship #F498AD
participant "ui:Ui" as Ui #8CB6CE

[-> RejectOfferCommand : execute()
activate RejectOfferCommand

RejectOfferCommand -> Parser : getParamsOf("reject")
activate Parser
Parser --> RejectOfferCommand : params
deactivate Parser

note right of RejectOfferCommand
  Parses index and
  validates bounds
end note

RejectOfferCommand -> InternshipList : get(index - 1)
activate InternshipList
InternshipList --> RejectOfferCommand : internship
deactivate InternshipList

RejectOfferCommand -> Internship : markAsRejected()
activate Internship
Internship --> RejectOfferCommand
deactivate Internship

RejectOfferCommand -> Ui : print("Rejection builds character! 💪...")
activate Ui
Ui --> RejectOfferCommand
deactivate Ui

[<-- RejectOfferCommand
deactivate RejectOfferCommand

@enduml