@startuml

class GoldenCompass {
    - internships : InternshipList
    - interviews : InterviewList
    + run()
}

class Executor {
    - Map<String, Command> commands
    + execute()
    + addAlias(command, alias)
    + getAliasMap()
}

interface Executable {
    + execute()
}

abstract class Command {
    - <u>FLAG_MISSING_MESSAGE : String
    + Command()
    + Command(Parser)
    + execute() : void
    # getCommandDescription() : String {abstract}
    # getFlagDescription() : String {abstract}
    # printHelp() : void
}

class UpcomingCommand {
    + UpcomingCommand(parser : Parser, interviewList : InterviewList)
    + execute() : void
    # getCommandDescription() : String
    # getFlagDescription() : String
}

class InterviewList {
    + getInterviews()
}

class Interview {
    - Internship internship;
    - LocalDate date;
    + setDate()
    + getDate()
    + toString()
    + getInternship()
}

class Ui {
    + print(message : String)
    + greet()
    + read()
}

class Parser {
    - <u>FLAGSET : Set<String>
    - flagToParamMap : Map<String, List<String>>
    + parse(userInput : String) : void
    + getCommand() : String
}

GoldenCompass --> "1" Executor
GoldenCompass --> "1" InterviewList
GoldenCompass --> "1" Ui
GoldenCompass --> "1" Parser

Executor -.> Command
Executor --> "1" Parser

Command --.|> Executable
UpcomingCommand --|> Command

UpcomingCommand --> "1" InterviewList
InterviewList o--> "*" Interview

Command --> "1" Ui
Command --> "1" Parser

@enduml